// IMDB TOP 250 Movies

module.exports = [
  "XXXTentacion",
  "Metallica",
  "Ed Sheeran",
  "Drake",
  "Imagine Dragons",
  "Post Malone",
  "Kendrick Lamar",
  "Scotty McCreery",
  "Bruno Mars",
  "Migos",
  "Camila Cabello",
  "Chris Stapleton",
  "Cardi B",
  "Logic",
  "Shawn Mendes",
  "Dua Lipa",
  "Halsey",
  "The Decemberists",
  "Maroon 5",
  "Justin Timberlake",
  "Charlie Puth",
  "Jason Aldean",
];
